import React, { useEffect, useMemo, useState } from "react";
import { ShoppingCart, Trash2, Send, Search } from "lucide-react";

const WHATSAPP_NUMBER = "34670716744";

const departments = [
  {
    name: "AGUA",
    products: [
      "AGUA FUENTELAJARA 1.5L",
      "AGUA LANJARON 1.5L PACK 6",
      "AGUA FUENTELAJARA 0.5L",
      "AGUA LANJARON 0.5L",
      "AGUA VALTORRE 0.5L PITORRO",
      "AGUA VALTORRE GARRAFA 5L",
      "AGUA SOLAN CABRAS 1.5L",
      "SOLAN CABRAS 500ML",
      "AGUA GOURMET CON GAS 0.5L",
      "AGUA GOURMET CON GAS 1.5L",
    ],
  },
  {
    name: "REFRESCOS LATAS",
    products: [
      "COCA COLA LATA 33CL",
      "COCA COLA ZERO LATA 33CL",
      "COCA COLA ZERO S/CAF 33CL",
      "FANTA NARANJA LATA 33CL",
      "FANTA LIMON LATA 33CL",
      "AQUARIUS NARANJA LATA 33CL",
      "AQUARIUS LIMON LATA 33CL",
      "SEVEN UP LATA 33CL",
      "PEPSI COLA LATA 33CL",
      "NESTEA MARACUYA LATA",
      "NESTEA LIMON LATA",
      "NESTEA FRUTOS ROJOS LATA",
      "TONICA LATA 33CL",
      "SIMON LIFE NARANJA LATA 33CL",
      "SIMON LIFE MANGO LATA 33CL",
      "T. VERANO LIMON CASERA LATA",
    ],
  },
  {
    name: "REFRESCOS 2L / 1.5L",
    products: [
      "COCA COLA 2L",
      "COCA COLA ZERO 2L",
      "COCA ZERO S/CAFEINA 2L",
      "FANTA NARANJA 2L",
      "FANTA LIMON 2L",
      "SEVEN UP 2L",
      "REVOLTOSA COLA 2L",
      "REVOLTOSA NARANJA 2L",
      "REVOLTOSA LIMON 2L",
      "CASERA LIMON 1.5L",
      "CASERA NARANJA 1.5L",
      "CASERA BLANCA 1.5L",
      "AQUARIUS NARANJA 1.5L",
      "AQUARIUS BLANCO 1.5L",
      "NESTEA MARACUYA 1.5L",
      "NESTEA 1.5L",
      "NESTEA FRUTOS ROJOS 1.5L",
      "SIMON LIFE NARANJA 1.5L",
      "SIMON LIFE MANDARINA 1.5L",
      "SIMON LIFE MANGO 1.5L",
      "PEPSI COLA 1.75L",
      "TONICA SCHWEPPES 1L",
      "LIMON&NADA MINUTE MAID 1L",
    ],
  },
  {
    name: "ZUMOS",
    products: [
      "BIOFRUTA PASCUAL TROPICAL P3",
      "BIOFRUTA PASCUAL PACIFICO P3",
      "BIOFRUTA PASCUAL IBIZA P3",
      "BIOFRUTA PASCUAL 1L TROPI",
      "FUNC. D.SIMON TROPICAL P6",
      "FUNC. D.SIMON CARIBE P6",
      "FUNC. D.SIMON MEDITERRANEO P6",
      "ZUMO D.SIMON PIÑA P6 200",
      "ZUMO D.SIMON MELOCOTON P6 200",
      "ROSTOY MELOCOTON 33CL",
      "ROSTOY PIÑA COCO 33CL",
      "ZUMO JUVER PIÑA 850ML",
      "ZUMO JUVER MELOCOTON 850ML",
      "ZUMO JUVER NARANJA 850ML",
    ],
  },
  {
    name: "KUYX 3L",
    products: [
      "KUYX NARANJA 3L",
      "KUYX TROPICAL 3L",
      "KUYX MANDARINA 3L",
      "KUYX FRUTOS DEL BOSQUE 3L",
      "KUYX PIÑA 3L",
      "KUYX PIÑA COCO 3L",
      "KUYX OCEANICO 3L",
    ],
  },
  {
    name: "KUYX 330ML",
    products: [
      "KUYX 330ML NARANJA",
      "KUYX 330ML MANDARINA",
      "KUYX 330ML TROPICAL",
      "KUYX 330ML PIÑA",
      "KUYX 330ML OCEANICO",
      "KUYX 330ML MANGO",
      "KUYX 330ML FRUTOS ROJOS",
    ],
  },
  {
    name: "ENERGÉTICAS",
    products: [
      "CAMALEON 250ML",
      "CAMALEON GRANDE 50CL",
      "POWER KING 25CL",
      "POWER KING GRANDE 50CL",
      "RED BULL 250ML",
      "RED BULL SIN AZUCAR 250ML",
      "MONSTER VERDE LATA 50CL",
      "MONSTER ULTRA WHITE 50CL",
      "MONSTER ZERO VERDE 50CL",
      "MONSTER MANGO 50CL",
      "MONSTER AZUL 50CL",
      "BURN LATA 500ML",
      "LOCURA LATA 50CL",
      "LOCURA COCO LATA 50CL",
      "LOCURA ENERGY DRINK PEQUEÑO",
      "ENERDRINK COCO Y PIÑA",
      "ENERDRINK FRESA SALVAJE",
      "ENERDRINK MORA",
      "ENERDRINK MANZANA",
      "ENERDRINK TARTA QUESO",
      "ENERDRINK COCO LOCO",
      "POWERADE ICE 50CL",
      "POWERADE BLOOD 50CL",
      "ENERYETI PIRULETA 500ML",
    ],
  },
  {
    name: "CERVEZAS",
    products: [
      "CERVEZA CRUZCAMPO LATA 33CL",
      "CERVEZA ESTRELLA SUR LATA",
      "ESTRELLA 0.0 LATA 33CL",
      "CRUZCAMPO S/A LATA 33CL",
      "RADLER LIMON CRUZCAMPO LATA",
      "HEINEKEN LATA 33CL",
      "CERVEZA CRUZCAMPO 50CL",
      "ESTRELLA SUR 50CL LATA GRANDE",
      "CERVEZA CRUZCAMPO 1L",
      "CERVEZA CRUZ DEL SUR 1L",
      "CERVEZA ESTRELLA 1L",
      "CERVEZA ESTRELLA 0.0 1L",
      "CRUZCAMPO ROSCA 1L",
      "CRUZCAMPO 750ML",
      "CRUZCAMPO PACK 6",
      "CRUZCAMPO BOTELLIN CAJA 24",
      "CRUZCAMPO BOTELLIN CAJA 20",
      "CRUZCAMPO SIN ALCOHOL PACK",
      "ESTRELLA DEL SUR PACK 6",
    ],
  },
  {
    name: "VINOS Y LICORES",
    products: [
      "VINO BLANCO GRAN DUQUE 1L",
      "VINO TINTO GRAN DUQUE 1L",
      "VINO BLANCO RIVILLA 2L",
      "VINO TINTO RIVILLA 2L",
      "VINO TINTO DON SIMON 1L",
      "VINO BLANCO DON SIMON 1L",
      "VINO RIOJA SEÑORES 3/4",
      "TINTO VERANO CASERA 1.5L",
      "RON CACIQUE 70CL",
      "RON BARCELO AÑEJO 70CL",
      "RON NEGRITA 70CL",
      "WHISKY WHITE LABEL 70CL",
      "WHISKY BALLANTINES 70CL",
      "WHISKY J&B 70CL",
      "GINEBRA LARIOS 1L",
      "GINEBRA BEEFEATER 70CL",
      "BRANDY TERRY 1L",
      "ANIS CASTELLANA 70CL",
      "LICOR MIURA 70CL",
      "MINI WHISKY WHITE LABEL",
      "MINI J. WALKER ROJA",
      "MINI RON BARCELO",
      "MINI BALLANTINES",
    ],
  },
  {
    name: "LÁCTEOS",
    products: [
      "LECHE COVAP ENTERA 1L",
      "LECHE COVAP SEMIDESNATADA 1L",
      "LECHE COVAP SIN LACTOSA ENTERA 1L",
      "LECHE COVAP SIN LACTOSA SEMI 1L",
      "LECHE PULEVA ENTERA 1L",
      "LECHE PULEVA SEMI 1L",
      "BATIDO PULEVA CACAO 1L",
      "BATIDO PULEVA FRESA 1L",
      "BATIDO PULEVA VAINILLA 1L",
      "BAT.PULEVA CACAO P6 200",
      "BAT.PULEVA FRESA P6 200",
      "BAT.PULEVA VAINILLA P6 200",
      "CAFE FRIO LANDESSA CAPUCHINO",
      "CAFE FRIO LANDESSA CON LECHE",
      "CAFE FRIO LANDESSA SOLO",
      "CAFE FRIO LANDESSA CARAMELO",
      "CAFE FRIO LANDESSA VAINILLA",
      "MARGARINA TULIPAN 225G",
      "MARGARINA TULIPAN 400G",
      "NATA COCINA RENY PICOT 200ML",
    ],
  },
  {
    name: "ALIMENTACIÓN",
    products: [
      "ACEITE GIRASOL ROSIL 1L",
      "ACEITE GIRASOL ROSIL 5L",
      "ACEITE OLIVA VIRGEN ROSIL 1L",
      "AZUCAR 1KG",
      "SAL FINA 1KG",
      "SAL GRUESA CHALUPA 1KG",
      "TOMATE FRITO ORLANDO 400G",
      "TOMATE FRITO ORLANDO 800G",
      "TOMATE FRITO ORLANDO 350G",
      "TOMATE FRITO MARTINETE 810G",
      "TOMATE FRITO MARTINETE 400G",
      "TOMATE TRITURADO MARTINETE 810G",
      "TOMATE TRITURADO MARTINETE 400G",
      "YATEKOMO POLLO 60G",
      "CALDO G.BLANCA POLLO 1L",
      "GARBANZOS FRASCO 560G",
      "PAN RALLADO PANAERAS 300G",
      "ARROZ BRILLANTE 1KG",
      "ARROZ BRILLANTE 500G",
      "MAYONESA YBARRA 450G",
      "KETCHUP ORLANDO 265G",
    ],
  },
  {
    name: "APERITIVOS",
    products: [
      "PIPAS SEVILLANAS",
      "REBUJINAS SEVILLANAS 120G",
      "RISKETOS 120G",
      "BUSCALIOS BARBACOA",
      "TOSTAITOS SEVILLANOS",
      "PATATAS HISPALANA 140G",
      "PRINGLES CREAM ONION 70G",
      "PRINGLES ORIGINAL 70G",
      "PRINGLES ORIGINAL 165G",
      "BOLAS MATCHBALL 105G",
      "REVUELTO CARTUJANO 120G",
      "PATATAS RUEDAS 100G",
      "TOTAS ESTILO CASERO 100G",
      "TOTAS CAMPESINA 100G",
      "GOFRE CON CHOCO 110G",
      "PALOMITA KETCHUP MOSTAZA 8U",
    ],
  },
  {
    name: "LIMPIEZA",
    products: [
      "LEJIA PINO PERFUMADA KIRIKO 2L",
      "LEJIA AMARILLA KIRIKO 2L",
      "LEJIA LAVADORA KIRIKO 2L",
      "LEJIA + DETERGENTE KIRIKO 2L",
      "LEJIA LIMON PERFUMADA KIRIKO 2L",
      "DETERGENTE KIRIKO MARSELLA 3L",
      "DETERGENTE KIRIKO BASICO 2.8L",
      "LAVAVAJILLAS FLOTA 1.1L",
      "FLOTA VAJILLAS 750ML",
      "FREGASUELOS PINO KIRIKO 1.5L",
      "FREGASUELOS DAMA NOCHE 1.5L",
      "FREGASUELOS J.MARSELLA 1.5L",
      "FREGASUELOS SPA 1.5L",
      "LIMPIACRISTALES KIRIKO 500ML",
      "PAPEL HIGIENICO FAMADIS 6R",
      "HIGIENICO ECONOMICO P12",
      "SECAMANO BUENO",
      "TOALLITAS BEBE 120U",
      "ESCOBA PRIMER PRECIO",
      "PASTA COLGATE 75ML",
    ],
  },
  {
    name: "VARIOS",
    products: [
      "ANDALUZA CAJA 47U",
      "ANDALUZA GOURMET CAJA 54U",
      "VIENA ARTESANA CAJA 65U",
      "HUEVOS P12 L",
      "BANDEJA T89 NEGRA",
      "BOLSA VERDE OFERTA 42X53",
      "BOLSA BLANCA 42X53 1KG",
      "ROLLO COMPOSTABLE 30X40 1KG",
      "BOLSA BASURA COMUNIDAD 180L",
      "BOLSA BASURA NORMAL 30L",
      "BOLSAS PANADERIA 30X43",
      "SERVILLETA DOBLE BLANCA P2",
      "ARENA GATO MIC&FRIENDS 5KG",
      "VASO PLASTICO 350CC",
      "PAPEL OCB 100U",
      "CARBON",
      "PAPEL ALUMINIO IND",
      "FILM INDUSTRIAL 200M",
      "PASTILLAS ENCENDIDO",
      "ESTUCHES DE LOS REYES",
    ],
  },
  {
    name: "CHARCUTERÍA",
    products: [
      "CHOPPED TERNERA CAMPOFRIO KG",
      "CHOPPED CERDO CAMPOFRIO KG",
      "QUESO GOUDA BARRA KG",
      "QUESO SEMI PUROVI 1.50E",
      "POLLO RELLENO CARLOTEÑA KG",
      "POLLO RELLENO BLANCE KG",
      "LOMO AL HORNO FAMADESA KG",
      "MAGRETA AL AJILLO FAMADESA KG",
      "JAMON COCIDO 1A KG",
      "PALETA REVILLA KG",
      "PECHUGA PAVO NOEL KG",
      "PECHUGA PAVOFRIO KG",
      "CHORIZO EXTRA VILLAR KG",
      "CHORIZO TRADICIONAL KG",
      "CHORIZO CULAR IBERICO KG",
      "SALCHICHON TURON KG",
      "CHOPPED BEEF CAMPOFRIO 95G",
      "CHOPPED CERDO CAMPOFRIO 95G",
      "MORTADELA SICILIANA 95G",
      "MORTADELA C/A CAMPOFRIO 95G",
      "JAMON CURADO NAVIDUL 50G",
      "PECHUGA PAVO CAMPOFRIO 70G",
      "JAMON COCIDO EXTRA 75G",
      "CHORIZO REVILLA 65G",
      "CHORIZO PAMPLONA REVILLA 65G",
      "SALAMI REVILLA 65G",
      "SALCHICHON REVILLA 65G",
      "TAQUITOS NAVIDUL 50G",
      "BACON O.MAYER 100G",
      "SALCHICHAS CAMPOFRIO FRANKFURT",
      "OFERTAS PIZZAS C.FRIO",
      "PIZZA CAMPOFRIO 4 QUESOS",
      "PIZZA CAMPOFRIO JAMON QUESO",
      "PIZZA CAMPOFRIO BOLOÑESA",
      "PIZZA CAMPOFRIO CARBONARA",
      "PIZZA CAMPOFRIO BARBACOA",
      "PIZZA JAMON BACON CEBOLLA",
      "PIZZA PEPPERONI CAMPOFRIO",
      "PIZZA POLLO KANSAS",
      "PIZZA POLLO MOSTAZA MIEL",
      "PIZZA SALSA MEXICANA",
    ],
  },
];

// Pega aquí todos los artículos del PDF. El código elimina automáticamente los repetidos con departments.
const hiddenProductsRaw = [
  const hiddenProductsRaw = [
  const hiddenProducts = [
  "( COMPOSTABLE ) 30 X 40 MERCADO ROLLO ANONIMA 1 KG",
  "1/2 LONCHA JAMON CUR.NAVIDUL 50GR",
  "15 x 30 BOLSA TRAMPARENTE",
  "355ML RED BULL GRANDE",
  "50 CL ESTRELLA SUR LATA GRANDE",
  "ABRILLANTADOR MICAL MAQUINAS 5L",
  "ABSOLUTE 200 ML ( PETACA )",
  "ABSOLUTE MINIATURA",
  "ACEITE GIRASOL ROSIL 1 L.(CAJAS 15 U)",
  "ACEITE GIRASOL ROSIL 5 L.",
  "ACEITE OLIVA VIRGEN 1 L ROSIL",
  "ACEITUNAS OFERTA SIN HUESO UNIDAD",
  "ACOND ANIAN NATURAL 1000",
  "AGRIO DE LIMON GOURMET 1/2",
  "AGUA 1/2 GOURMET CON GAS",
  "AGUA DESIONIZADA 2L KIRIKO",
  "AGUA FONT VELLA 1.5 L",
  "AGUA FUENTELAJARA 1.5 L.",
  "AGUA FUENTELAJARA 1/2",
  "AGUA FUERTE 1.5L KIRIKO",
  "AGUA GOURMET MINERAL CON GAS 1.5",
  "AGUA LANJARON 0,75L 15 UNID.",
  "AGUA LANJARON 1.5 L.(P-6)",
  "AGUA LANJARON S/G 6 L TAPON GR",
  "AGUA OXIGENADA KELSIA 250",
  "AGUA SOLAN DE CABRAS S/G 1,5 L.",
  "AGUA SOLAN DE CABRAS S/G 5L GFA",
  "AGUA VALTORRE 1/2 PITORRO",
  "AGUA VALTORRE TREKKING 0.75",
  "AGUASAL PIPAS (SEVILLANAS)",
  "AJO GRANULADO LA BARRACA BTE PEQUEÑO",
  "AJO PEREJIL LA BARRACA BTE PEQUEÑO",
  "AJONJOLI DORADO LA BARRACA BTE PEQUEÑO",
  "ALBAHACA BARRACA BTE PEQUEÑO",
  "ALBONDIGAS ABRICOME LAT 420 SALSA",
  "ALBONDIGAS C/GUISAN LOURIÑO L/425",
  "ALBONDIGAS LOURIÑO L/425",
  "ALCACHOFA DIAMIR 6/8 LT 390 GR",
  "ALCOHOL MICADERM SANITARIO 250 ML",
  "ALTRAMUZ SALADITO BANDEJA 250GR C/10",
  "ALUBIA FRASCO 570 GR",
  "ALUBIAS BLANCA 1/2 KG",
  "ALUMINIO DOMESTICO 30",
  "ALUMINIO DOMESTICO 8 METROS",
  "AMONIACO NORMAL KIRIKO 1.5LT",
  "AMONIACO PERFUMADO 1.5L KIRIKO",
  "AMONIACO PQS 1 L.",
  "ANCHOAS CAPRIMAR ABRE F.",
  "ANDALUZA CAJA ( 47 UNIDADES )",
  "ANDALUZA GOURMET ( CAJA 54 UNIDADES )",
  "ANIS ARENA SECO 1 L.",
  "ANIS CASTELLANA 70CL 35º",
  "APETINAS KETCHUP 25G",
  "APETINAS KETCHUP 90G",
  "APPEL MELON ENERGETICO POWER KING 25CL",
  "AQUAPLUS LIMON 1.5 L VALTORRE",
  "AQUARIUS BLANCO 1.5 L",
  "AQUARIUS NARANJA LATA 33 CL.",
  "ARENA GATO MIC&FRIENDS PERFUMADA 5K",
  "ARIEL LIQ 28D",
  "ARROZ BRILLANTE 1 KG",
  "ARROZ BRILLANTE 500 GR",
  "ARROZ BRILLANTE BASMATI 2X125 GR",
  "ARROZ CIGALA 500 GR.",
  "ARROZ SOS 1/2",
  "ATUN DIAMIR 1KG",
  "ATUN PESCAMAR TOMATE RO-80 AF",
  "ATUN RAZO AC/VEG. PACK 3 ABREFACIL",
  "AVECREM PESCADO 8 PASTILLAS",
  "AVECREM POLLO 8",
  "AZUCAR 1 K",
  "AZUCAR AZUCARERA MORENO PPC 800G",
  "AZUCAR SOBRES 10GR CONSEMUR",
  "BACARDI 200 ML ( PETACA )",
  "BACON CASA TARRADELLAS 2X100G",
  "BACON PROLONGO,KG",
  "BACON SUAVE O.MAYER LOCHAS 100GR 1,50E",
  "BAILEYS ORIGINAL 70CL",
  "BALLANTINES MINIATURA",
  "BANDEJA T89 U (NEGRAS)",
  "BANDERILLA GOURMET PICA.150G",
  "BASTONCILLOS ALGODON COALIMENT 200UDS",
  "BAT.PULEVA CACAO P-6 200",
  "BAT.PULEVA FRESA P-6 200",
  "BAT.PULEVA VAINILLA P-6 200",
  "BATIDO PULEVA CACAO LITRO",
  "BATIDO PULEVA FRESA LITRO",
  "BATIDO PULEVA VAINILLA LITRO",
  "BAYETA MICAL 1 UNIDAD MICRIFI 38X40",
  "BAYETA MICAL AMARILLA 40X36 CM 10U",
  "BAYETA MICAL MICROFIBRA BAÑO 38X40 2U",
  "BEBIDA ENERYETI DRAGON 500ML",
  "BEBIDA ENERYETI PIRULETA LATA 500ML",
  "BERBERECHO DIAMIR RR-120 70/80",
  "BICARBONATO LA BARRACA 180 GR",
  "BIOFRUTA PASCUAL 1 L TROPI",
  "BOBINA P.V.C. 45X1500",
  "BOL GRANDE",
  "BOL PEQUEÑO",
  "BOLAS MATCHBALL 105G 10U",
  "BOLSA 30X40 ASA KG FUERTE CAMISETA B.O 70% SEGUN LEY",
  "BOLSA 35X50 ASA FINA 200 U CAMISETA",
  "BOLSA BASURA 115X150 SUPER GRANDE CARNICERIA",
  "BOLSA BASURA COMUNIDAD 90X115 180L",
  "BOLSA BASURA NORMAL 30L 55X60",
  "BOLSA BLANCA 35X50 1KG NORMA",
  "BOLSA BLANCA 42X53CM 1 KG RECICLADA IMPRESA",
  "BOLSA BLANCA 50x60 GRANDE BLANCA",
  "BOLSA FINAS PANADERIA 30X43",
  "BOLSA VERDE (OFERTA) 42X53",
  "BOLSAS 10X20 PURUÑUELA",
  "BOLSAS 12X25 PURUÑUELA",
  "BOTELLIN JUVER MELOCOTON",
  "BOTELLIN JUVER PIÑA",
  "BRANDY CENTENARIO TERRY 1 L.",
  "BRANDY MAGNO 70 CL.",
  "BROTES DE SOJA GOURMET 180G",
  "BUDIN PROLONGO 150GR",
  "BURN LATA 500 ML",
  "BUSCALIOS 140 X 12 CORTEZA BARBACOA RISI",
  "CABALLA ACEITE/V UBAGO 90",
  "CABALLA UBAGO TOMATE 90G",
  "CABALLERO GARBANZO LECHOSO 1/2 K",
  "CABALLERO LENTEJA CASTELLANA 1/2 K",
  "CABALLERO VERDINA 1/2 KG",
  "CABECERO LOMO VIAN SANA 60G",
  "CABEZADA LOMO CARLOTEÑA,KG",
  "CAFE FRIO LANDESSA EXPRESO SOLO",
  "CAFE FRIO LANDESSA KAKAO",
  "CALAMAR MIAU AMERICANA RO-85P3",
  "CALAMAR MIAU TINTA RO-85P3",
  "CALDO G.BCA CASERO POLLO 1 L.",
  "CALDO GOURMET POLLO 1L",
  "CALLOS APIS LT 390 GR",
  "CALLOS CERDO 400GR MONTEALBOR",
  "CALLOS TERNERA 400GR MONTEALBOR",
  "CALLOS TERNERA BARRA MONTEALBOR,KG.",
  "CAMALEON GRANDE ESPAÑOL 50 CL",
  "CANELA MOLIDA LA BARRACA",
  "CANELA RAMA LA BARRACA",
  "CASCALES DOÑA PIPA JUVENIL DE 30 UN",
  "CASCALES GRANDE DOÑA PIPA 14 U",
  "CASERA BLANCA 1.5 L.",
  "CASERA BLANCA LATA",
  "CASERA LIMON 1.5",
  "CASERA NARANJA 1.5",
  "CAVA SEMI SECO BONAVAL 3/4",
  "CENTRO J.CURADO NAVIDUL KG",
  "CERVEZA 0.0 ESTRELLA 1 L.",
  "CERVEZA 50CL CRUZCAMPO",
  "CERVEZA CRUZCAMPO BOTELLIN P24",
  "CERVEZA CRUZCAMPO BOTE . PACK 6",
  "CERVEZA CRUZCAMPO S/A LATA 33CL",
  "CERVEZA CRUZCAMPO UNIDAD S/A P-6",
  "CERVEZA ESTRELLA 0.0 LATA",
  "CERVEZA ESTRELLA 1 L.",
  "CERVEZA ESTRELLA DEL SUR P-6",
  "CHAMPIÑON GOURMET ENTERO 185GR",
  "CHAMPIÑON NAT.LAMINADO L/500",
  "CHOPPED BEEF CAMPOF.L/95GR",
  "CHOPPED CERDO CAMPOF.L/95 GR",
  "CHOPPED CERDO CAMPOFRIO,KG",
  "CHOPPED PAVO L/95 GR CAMPOF.",
  "CHOPPED PORK LATA 2 KG FAMADESA",
  "CHOPPED TERNERA CAMPOFRIO,KG",
  "CHORIZO BLANCO 65 GR",
  "CHORIZO CULAR IBERICO 1ª ,KG",
  "CHORIZO EXTRA ESPECIAL VILLAR AL VACIO KG",
  "CHORIZO IBER.LONCHA 45G NAVIDUL",
  "CHORIZO PAMPLONA REVILLA LON 65 GR",
  "CHORIZO PICANTE REVILLA L/65 GR",
  "CHORIZO REVILLA TAQUITOS 65GR",
  "CHORIZO TRAD. REVILLA 65GR",
  "CHORIZO TRADICIONAL REVILLA,KG",
  "CHORIZO TUNEL PIMI.LONCHA 80GR PROLONGO",
  "CHORIZO TURON TUNEL PIMIENTA 1/2 PIEZA",
  "CHORIZO Y MORCILLA IBERICOS VACIO 200G",
  "CHOVI ALIOLI 250 ML.(ALI-OLI)",
  "CHURRUCA KIKONAZO PLUS 50 UNID.",
  "CHURRUCA PASARRATOS EJECUTIVE 10UDS",
  "CHURRUCA PASARRATOS SENIOR 20UDS",
  "CLAVO GRANO LA BARRACA BTE CRISTAL",
  "COCA COLA 2 L.",
  "COCA COLA 2 L. ZERO",
  "COCA COLA LATA 33 CL",
  "COCA COLA ZERO LATA 33 CL",
  "COCA COLA ZERO S/CAFEINA 2L",
  "COCA COLA ZERO S/CAFEINA LTA 33CL",
  "COCIDO MADRILEÑO LITORAL 440GR",
  "COCINA FAMADIS LIMON ROLLOM P-2",
  "COCINA NICKY LIMON ROLLO P-2",
  "COCO PIÑA POWER KING 25CL",
  "COLA-COLA CAO 400",
  "COLONIA MECADERM INF 750 ML",
  "COLORANTE LA BARRACA",
  "COMIDA GATO MIC&FR.MIX CARNR 4K",
  "COMIDA MIC&FR. PERRO BUEY 300GR",
  "COMIDA MIC&FR. PERRO POLLO 300GR",
  "COMIDA PERRO MIC&FRIENDS 4K",
  "COMINO GRANO LA BARRACA B/PEQUEÑO",
  "COMINO MOLIDO LA BARRACA BTE PEQUEÑO",
  "COMP AFECTIVA NOCHE 10U",
  "COMP AFECTIVA NOCHE ALA 14U",
  "COMP AFECTIVA ULTRA ALA 16U",
  "COMP. EVAX FINA Y SEGURA NORM 16 U",
  "COMPANGO 3X100 GR",
  "COMPRESA AFECTIVA ECONOMICA EST.20 UNI",
  "COMPRESA FINA Y SEG.ALAS NORMAL EVAX 12U",
  "CONOS VAINILLA Y CHOCOLATE 4 SOMOSIERRA",
  "CORTEZAS 100 GR CARTUJANO",
  "CR CACAO NOCILLA 190 DUO",
  "CR CACAO NOCILLA 190 ORIGINAL",
  "CUCHILLA GILLETE BLUEII 5+1",
  "CUBO FREGONA KARIN + ESCURRIDOR",
  "CUBO PESTIÑOS SERAFIN 800 GR",
  "CURRY BARRACA BOTE CRISTAL PEQUEÑO",
  "CUÑA DE QUESO RESERVA PREC.200 GR.CAMP.",
  "CUÑA QUESO CABRA PRECORT.CAMPOF.200 GR",
  "CUÑA QUESO SEMI NAVIDUL 170 GR",
  "C.V ESPUMOSO ROSADO \"MAGNA\"",
  "DELICIA SURIMI,KG",
  "DESENG NUCA MAX 1L PERFUMADO EL MILAGRITO",
  "DESENGRASANTE AGERUL PIST 750",
  "DESENGRASANTE PISTOLA 750 KIRIKO",
  "DESOD.DOVE ORIGINAL SP 250ML",
  "DETE LIQ. 5L LUCECITA ORIGINAL KIRIKO 5L",
  "DETE LIQ. LUCECITA AZUL KIRIKO 5L",
  "DETE LIQ. LUCECITA J MARSELLA KIRIKO 5L",
  "DETER.LIQ HIGIENIZANTE 3L KIRIKO",
  "DETER.LIQ J.MARSELLA 3L KIRIKO",
  "DETERG.LIQ.MARSELLA 2 L.KIRIKO",
  "DETERGENTE LIQ. BASICO NORMAL KIRIKO 2.8L",
  "DETERGENTE LUCECITA 2.8L ORIGINAL 2.8L",
  "DULCE MEMBRILLO QUIJOTE 400 GR",
  "EDULCORANTE DOSIF.650 COMP.LA BARRACA",
  "ELIXIR MICADERM MENTA 500 ML",
  "ENERDRINK SANDIA Y UVA",
  "ENERYETI ATOMYC",
  "ENJOY 1/2 L NARANJA",
  "ENSALADA PIMIEN.ASAD.ALSUR L/420GR",
  "ESPAR TRIG ALSUR TROC 390 GR AF",
  "ESPARRAGO GOURMET EXT.FCO 9/12 205G (8096)",
  "ESPECIAS DE CARACOLES GRANO LA BARRACA",
  "ESPECIAS SURT GRANO LA BARRACA BTE PEQUEÑO",
  "ESP. PINCHOS AMARILLOS LA BARRACA BTE .PEQUEÑO",
  "ESPINACAS ALSUR FRASCO 660GR",
  "ESPUMA AFEITAR GILLETE 200ML",
  "ESPUMA PERFE EF GIORGI 200",
  "ESTROPAJO FIBRA VERDE PACK",
  "ESTROPAJO MICAL SALVAUÑAS P-3",
  "ESTROPAJO MITALICO PACK",
  "EXOTICA GIN 1890 70CL",
  "F1 29G 30U KIT KAT",
  "FABADA ASTURIANA LITORAL LT 435 GR",
  "FAIRY 480",
  "FAIRY MAXI PODER",
  "FANTA LIMON 2 LITROS",
  "FANTA LIMON LATA 33 CL",
  "FANTA NARANJA 2 L",
  "FANTA NARANJA LATA 33 CL",
  "FIAMBRE CASADEMONT 11 X11 KG-DUCADO-",
  "FIAMBRE DE PALETA COCIDA CAMPOFRIO.KG",
  "FIAMBRE LOMO AL HORNO FAMADESA KG",
  "FIDEOS GALLO Nº0 250 GR",
  "FIDEOS GALLO Nº1 250 GR",
  "FIDEOS GALLO Nº2 250 GR",
  "FIDEOS GALLO Nº4 250 GR",
  "FIDEOS GALLO PERLA 250 GR",
  "FILETE CABALLA A/V DIAMIR 1000",
  "FILMS INDUSTRIAL 200 M (CORTO)",
  "FILMS INDUSTRIAL 45X300 (MELCHO)MORADO LARGO PARA FRUTA",
  "FINISH PLLAS TODO EN1 25+25u",
  "FLOTA LIQ 2.69 L 42+10 D A.PLUS BOUQUET",
  "FLOTA PASTILLAS VERDE NORMAL 250 G",
  "FLOTA VAJILLAS 750 ML",
  "FOIE-GRAS PIARA 75 GR P3",
  "FOIE-GRAS PIARA 800 GR",
  "FOIGRAS APIS 200 GR",
  "FOIGRAS APIS P3 80 GR NORMAL",
  "FOLIO",
  "FREGASUELO COLONIA 1.500 L KIRIKO",
  "FREGASUELOS ALOE VERA 1.5 L KIRIKO",
  "FREGASUELOS ASEVI CIAN 1L",
  "FREGASUELOS ASEVI MIO 1L",
  "FREGASUELOS ASEVI NARANJA 1L",
  "FREGASUELOS DAMA DE NOCHE 1.5L KIRIKO",
  "FREGASUELOS FLORAL 1.5 L KIRIKO",
  "FREGASUELOS J.MARSELLA 1.5L KIRIKO",
  "FREGASUELOS KIRIKO LIMON 1,5L",
  "FREGASUELOS PINO 1.5L KIRIKO",
  "FREGASUELOS SPA 1.5 LT KIRIKO",
  "FREGASUELOS TALCO 1.5L KIRIKO",
  "FREGONA MICAL ALGODON",
  "FREGONA MICAL AMARILLA",
  "FREGONA MICAL AZUL",
  "FREGONA MICAL MICROFIBRA",
  "FRESHYETI CANDI PLATANO 500 ML",
  "FRESHYETI PINTALENGUAS 500ML",
  "FUNC.MAX D.SIMON CARIBE 200 P-6 (5310)",
  "FUNC.MAX D.SIMON TROPICAL P-6 200 (5331)",
  "GALLETAS CHIQUILIN 525GR",
  "GALLOS HALCONERO 10 U",
  "GALLOS SUPER SENIOR XXL 10U",
  "GAMA FVL 1.25L LIMON",
  "GARBANZOS CONSEMUR 560GR",
  "GEL AF GILLETTE 200 SENS EXISTI",
  "GEL COALIMENT DERMO 750 ML",
  "GEL DERMO COALIMENT 750ML",
  "GEL FIJA GIORGI EXTRA FUERTE 240 N3 NEW",
  "GEL FIJA GIORGI MAX EXT FUERTE 240 N3 NEW",
  "GEL ICEBERG Y MENTA 750ML COALI",
  "GEL NELLY HUMEDO FUERTE 200",
  "GINEBRA BEEFEATER 70CL",
  "GINEBRA RIVES 0.70",
  "GINEBRA SEAGRAM´S 70CL",
  "GINEBRA TANQUERAY SEVILLA 0.7 L",
  "GINS LARIOS 70CL",
  "GIN PUERTO DE INDIAS 70CL",
  "GUISANTE LOZANO LT 185",
  "GUISANTES LOZANO LATA 500 GRS.",
  "GUSANITO ASPIL 36U",
  "HABAS BABY GOURMET 425G",
  "HARINA DE GARBANZO 500GR",
  "HARINA TRIGO GALLO REPOSTERIA 500 GR",
  "HIGIENICO 2C 12R ROL.GOF.46MT 480S.ECO",
  "HIGIENIZANTE MULTIUSOS 750 ML/KIRIKO",
  "HOJALDRE PLUS SERAFIN CORTADITOS 700G",
  "INSECT CASA JARDIN 600 SP ROSAS",
  "JABON DE MANOS COCINAS 500ML NAVINIA",
  "JABON DE MANOS DERMO 500ML NAVINIA",
  "JABON DE MANOS FRESA Y NATA 500ML NAVINIA",
  "JABUGUITO DULCE CABO 200GR",
  "JAGERMEISTER HERB 0.70CL",
  "JAMON COCIDO CAMPOFRIO,KG",
  "JAMON CURADO EXTRA NAVIDUL 50G",
  "JUDIA ANCHA CORTADA ALSUR FRASCO 660 G",
  "JUDIA VERDE BOBY ALSUR 660 GR AF",
  "JUDIAS C/CHORIZO LOZANO LT 425G",
  "JUDIAS VERDES FINAS ALSUR 660 FCO",
  "JUMMY 100GR 9U",
  "KELIA POLOS 60U 1SABOR",
  "KETCHUP PRIMA 325G",
  "KIKONAZOS SUPER SENIOR XXL 10U",
  "KINDER BUENO PACK 30U",
  "KINDER HAPPY HIPPO BOLSA 10 U",
  "KINDER T4 HUEVO 72U",
  "KIT KAT 3F 28G 30U",
  "LACA NELLY FUERTE 400 ML.",
  "LACA NELLY SP NORMAL",
  "LATA LENTEJAS ABRICOME 420GR",
  "LAUREL CAJA CARTON BARRACA 12U.",
  "LAVAVAJILLAS FLOTA 1.2L",
  "LAVAVAJILLAS MICAL MAQUINAS 5L",
  "LECHE CONDENSADA LA LECHERA 450G",
  "LEJIA AMARILLA KIRIKO 2L.",
  "LEJIA COLOR 1 LT KIRIKO",
  "LEJIA ESTRELLA PINO 1.5 L.",
  "LEJIA KIRIKO PINO 2L",
  "LEJIA LIMON ESTRELLA 1.5L",
  "LICOR AMARETTO DISARONNO 70 CL",
  "LICOR COCO-RON MALIBU 0.70",
  "LICOR CREMA DE ARROZ DOÑA P",
  "LICOR RUAVIEJA HIERBAS 70 CL",
  "LIMPIAHOGAR BAÑOS 1.500 KIRIKO",
  "LIMPIAHOGAR CON LEJIA KIRIKO 1.5L",
  "LIMPIEZA PISTOLA 1L LIMON KH7",
  "LOMITO IBERICO DE BELLOTA VILLAR KG",
  "LOMO HORNO FAMADESA, KG",
  "MACARRONES GALLO 250 GR",
  "MACARRONES VEGETALES GALLO 250 GR",
  "MACEDONIA VERDURAS ALSUR 660 FCO",
  "MAGRETA AL AJILLO FAMADESA, KG",
  "MAGRETA IB.FAMADESA KG",
  "MAIZ DULCE GOURMET DULCE 140G P-3",
  "MAIZENA PTE 400 GR",
  "MAIZ GOURMET DULCE 285GR",
  "MANGO 1.40 PINTADO ROJO (BARATO)",
  "MARGARINA TULIPAN 400G",
  "MAZA DE CERDO HORNEADA,KG",
  "MECHERO CLIPER TRANSPARENTE CAJA",
  "MEDIAS NOCHES BIMBO 8 UNIDADES",
  "MEJILLONES (20/30)RIA SULTAN PEQUEÑO DOP",
  "MELVA ACEITE DIAMIR RO 1KG",
  "MELVA CANUTERA DIAMIR LT RR125",
  "MENTA POLEO LA BARRACA 10 INF.",
  "MERMELADA FRESA LA VIEJA FABRICA 350GR",
  "MERMELADA MELOCOTON LA VIEJA FABRICA 350GR",
  "MIEL LA DULCE ABEJA 1KG",
  "MINI APENINAS KRTCHUP 24G 0.50€",
  "MINI APENINAS QUESO 24G 0.50€",
  "MINI BANANA 28G",
  "MINI BITS SABOR CHOCOLATE 32G",
  "MINI CRESTAS KETCHUP 20G",
  "MINI FUET CAMPOFRIO 50 GR",
  "MINI HOT DOG 80G",
  "MINI OSITOS 30G",
  "MINI PICOTEO 30G",
  "MISTELA LA PASERA 1.5 L.",
  "MOJAMA ATUN USISA KG",
  "MORTADELA CLASICA CAMPOF.KG.",
  "MORTADELA PAVO CAMPOFRIO,KG",
  "MORTADELA SICILIANA 95G CAMPOFRIO",
  "MORTADELA SICILIANA C/A ,KG",
  "MOUSE LIMPIADOR 750ML KIRIKO",
  "NATA SPRAY KELSIA 250G",
  "NERVION BLANCO 1L",
  "NEVADITOS MINIS 400 GR",
  "NUEVA REVOLTOSA COLA 2L",
  "NUEZ MOSCADA LA BARRACA BTE PEQUEÑO",
  "OREGANO HOJA LA BARRACA BOTE",
  "OREGANO MOLIDO LA BARRACA BOTE",
  "PACHARAN ZOCO 1 L.",
  "PAJITAS PAPEL 200 U",
  "PALET CHEP AZUL",
  "PALET CHEP ROJO",
  "PALETA REVILLA 1/2 VACIO,KG",
  "PALETA REVILLA AL CORTE,KG",
  "PALOMITA ASPIL 20 U",
  "PAN BURGUER 4U 200G",
  "PAN CAMPESTRE 460G",
  "PAN HOT DOG 4U 200G 1€",
  "PAN MEDIANOCHE 250G",
  "PAN MOLDE 410G €",
  "PAN MOLDE 460G ALTO",
  "PAN MOLDE 820G",
  "PAN MOLDE INTEGRAL 460G",
  "PAN MOLDE INTEGRAL 820G",
  "PAN MOLDE RUSTIK INTEGRAL 450G",
  "PAN MOLDE RUSTIK SESAMO Y LINO 450G",
  "PAN RAYADO PANAERAS 300GR",
  "PAPEL ALUMINIO IND.",
  "PAPEL FILMS MERCASUR 30 M",
  "PAPEL HORNO 8 METROS COALI",
  "PAPEL OCB 100 UNID",
  "PAPEL OCB 100 UNIDADES",
  "PASARRATOS SUPER SENIOR XXL 10U",
  "PASTA GALLO ESTRELLAS 250GR",
  "PASTA GALLO FIDEUA 250 GR",
  "PASTA GALLO HELICE C/VGET 250",
  "PASTA GALLO LETRA 250GR",
  "PASTA GALLO PLUMA Nº6 250GR",
  "PATATA PREDILECTA 125G",
  "PATATAS AJO Y PEREJIL HISPALANA 140G",
  "PATATAS AL AJILLO HISPALANA 140G",
  "PATATAS AL PUNTO SAL HISPALANA 140G",
  "PATATAS CAMPESINA 165GR HISPA",
  "PATATAS FRITAS HISPALANA 140G",
  "PATATAS GOURMET BABY 420GR",
  "PATATAS JAMON 180G 1.5€",
  "PATATAS QUESO HISPALANA 140G",
  "PATATAS RUEDAS 100G 1€",
  "PATATAS SABOR BACON HISPALANA 140G",
  "PATATAS SABOR JAMON HISPALANA 140G",
  "PATATAS SERRANAS 180G 1.5€",
  "PATATAS TRADICIONAL 180G 1.5€",
  "PECHUGA DE PAVO ALMIREZ,KG",
  "PECHUGA DE PAVO CAMPOFRIO, KG",
  "PECHUGA PAVO ALMIREZ,KG",
  "PECHUGA PAVO BRASEADA CAMPOFRIO KG",
  "PECHUGA PAVO CAMPOFRIO 70G",
  "PEDRO XIMENEZ 3 PASAS",
  "PEPINILLOS DELICIAS 360 GR",
  "PEREJIL LA BARRACA BTE PEQUEÑO",
  "PESTIÑOS CARTUJANO CON MIEL 250G",
  "PIMENTON PICANTE BARRACA",
  "PIMIENTO M.ALSUR 370 TIRAS",
  "PIMIENTO MORRON EXTRA P-3",
  "PIMIENTO PIQUILLO DIAMIR 185G",
  "PIMIENTA NEGRA GRANO LA BARRACA BTE PEQUEÑO",
  "PIMIENTOS ASADOS 445GR. CRISTAL CAMPO RICO",
  "PINZA PLASTICO 24U",
  "PIÑA JUGO EXT DIAMIR P3 227",
  "PISTO ORLANDO LATA 410 GR",
  "PISTOLA NUCA MAX 1L PERFUMADO EL MILAGRITO",
  "PIZZA 4 QUESOS CAMPOFRIO 345G",
  "PIZZA ATUN-CEBOLLA S/TERIYAKI CAMPOF.",
  "PIZZA BOLOÑESA CAMPOFRIO 390GR",
  "PIZZA CARBONARA",
  "PIZZA JAMON BA.CON CEBOLLA CAMPOF.",
  "PIZZA JAMON Y QUESO CAMPOFRIO 370GR",
  "PIZZA POLLO KANSAS CAMPOFRIO 400GR",
  "PIZZA POLLO MOSTAZA MIEL CAMPOF.",
  "PIZZA SALSA MEXICANA CAMPOF.",
  "PIZZA SERRANA-CABRA-CEBOLLA CAMP.",
  "POLO KELIA 1SABOR 60 UN",
  "PONCHE CABALLERO 1L",
  "POWER KING 25CL",
  "PRINGLES ORIGINAL 70 GR",
  "PRINGLES SOUR CREAM CEBOLLA 70G",
  "PROTOS CRIANZA 201",
  "P.TRAN (80004) 4 8X200",
  "P.TRAN(80003) 1/2,1/4/ 4X1000 U. PRIMER PRECIO",
  "PULPA TOMATE TRITURADA MARTINETE 400G",
  "PULPO DIAMIR ACEITE OL-120",
  "PUNTOMATIC COLOR TUBO 8 UND.",
  "PUNTOMATIC TUBO 4 DOSIS BLANCO",
  "Q. APOLONIO ARTESANO CURADO",
  "QUESO APOLONIO CURADO KG",
  "QUESO APOLONIO SEMICURADO KG",
  "QUESO APOLONIO SEMI SIN LACTOSA KG",
  "QUESO BARUS GARCIA BAQUERO KG",
  "QUESO CABRA BARRA KG",
  "QUESO CERDO PROLONGO,KG",
  "QUESO DON APOLONIO ACEITE KG",
  "QUESO FRESCO 250GR LOS VAZQUEZ",
  "QUESO GOUDA BARRA GARCIA BAQUERO KG",
  "QUESO KIKO PLUS JUN.30 UNID",
  "QUESO MEZCLA SEMI G. BAQUERO AL CORTE KG",
  "QUESO PUROVIEJO SEMI PORTION 1.50€",
  "QUESO ROQUEFORT,KG",
  "QUITAMANCHAS ESPECIAL ROPA PULVERIZADOR KIRIKO",
  "RADLER CRUZCAMPO LIMON LATA",
  "RAMON BILBAO CRIANZA 2013 75CL",
  "REBUJINAS SEVILLANAS 120G",
  "RECAM MOPA PLA ATRAPAPOLVO 20 UN DESECH",
  "RECOGEDOR C/MANGO",
  "REFRESCO PINK FISH 2 L. COLA",
  "REFRESCO PINK FISH 2L LIMON",
  "REGAÑA ARTESANA 200GR ALABARDERO",
  "REMOLACHA CONSEMUR RALLADA TARRO S/370",
  "REVOLTOSA COLA 2 L",
  "REVOLTOSA LIMON 2 L",
  "REVUELTO CARTUJANO 120G 1€",
  "RIOJA T BERONIA CRIANZA 3/4",
  "RON AREHUCAS ORO 0.70 L",
  "RON BACARDI 1L",
  "RON BARCELO 1 L.",
  "RON BARCELO AÑEJO 0.70",
  "RON BRUGAL AÑEJO 0.70",
  "RON CACIQUE 70 CL.",
  "RON MIEL DORAMAS 70 CL.",
  "RON NEGRITA 1 L",
  "ROSTOY BIFRUTA MELOCOTON 33CL",
  "ROSTOY BIFRUTAS PIÑA COCO 33CL",
  "RULO CABRA SOIGNON 180 G",
  "SACAPUNTAS DOS ENTRADAS KUM",
  "SALCHICHA CAMPESANAS BRATV.PACK3",
  "SALCHICHA GIGANT KING S/CAMPOFRIO",
  "SALCHICHAS CAMPESAN PACK 3 CAMPOF.",
  "SALCHICHAS JAMON CAMPOF.PACK 3",
  "SALCHICHAS JUMBO CLASSIC OM 350G 14U",
  "SALCHICHAS OSCAR MAYER WIENERS 5U",
  "SALCHICHON 65G REVILLA",
  "SALCHICHON CUMBRE REAL CAMPOF.",
  "SALCHICHON REVILLA LONCHAS 65 GR",
  "SALCHICHON TRAD.REVILLA KG",
  "SALCHICHON TRADICIONAL PIEZA 250GR",
  "SALSA ALIOLI MONTEALBOR 180ML",
  "SALSA BOLOÑESA GALLO FCO 230 GR",
  "SALSA CESAR YBARRA 225ML",
  "SALSA COCKTAIL YBARRA 250 GR",
  "SALSA GAUCHA BOCABAJO 300ML",
  "SALSA KETCHUP BOCABAJO 300ML",
  "SALSA KETCHUP PRIMA 325GR",
  "SALSA PIRI-PIRI 195G MONTEALBOR",
  "SALSA VERDE 180GR MONTEALBOAR",
  "SALSA YBARRA ALI-OLI 225",
  "SALSA YBARRA ALI-OLI BOTE",
  "SALSA YBARRA GAUCHA 225 GR",
  "SANDWICH 3U NOCILLA 135G",
  "SARDINAS ACEITE F.A 90G",
  "SARDINAS TOMATE F.A 90G",
  "SAZONADOR CARNE LA BARRACA PEQUEÑOS",
  "SAZONADOR DE CARACOLES LA BARRACA",
  "SAZONADOR POLLO LA BARRACA BOTE",
  "SECRETO CABECERO KG PROLONGO",
  "SERVILLETA CELIA 30X30 2 HOJA 70U",
  "SERVILLETA CELIA 30X30 MORADA",
  "SERVILLETAS 33X33 2C BLANCA 50U FAMADIS",
  "SERVILLETAS 33X33 BLANCA 1C 200U",
  "SERVILLETAS 33X33 BLANCA 2C 100U",
  "SERVILLETAS CELIA 2C 40X40 50 UNIDADES",
  "SEVEN-UP LATA 33 CL",
  "SOPA G BCA 24 SB AVE C/ARROZ",
  "SOPA G.BLANCA TERNERA-ESTRELLA 24S",
  "SOPA G.BLANCA VERDURAS 24 S",
  "SUAV FLOR 2.2L 44D AZUL",
  "SUAV SAN 1.29L ESENCIAS PARA RECORDAR",
  "SUAV SAN 1.29L TALCO ROSA",
  "SUAVIZANTE SAN FLORAL 2.2L 44D",
  "SUAVIZANTE SPA 2L KIRIKO",
  "T ARRIBA CROCANTI 200G",
  "TAPADERA POREX 7 OZ B/100 U.",
  "TE LA BARRACA 10U.",
  "TENEDOR MESA 25U BLANCO PP",
  "TIBURON GALLO N 0 250 GR",
  "TILA BARRACA 10U.",
  "TINTO JOVEN RIOJA TORREALDEA 2024",
  "TINTO MISIVA RIBERA DUERO 2023",
  "TINTO RIOJA M CACERES3/4 CRIANZA",
  "TINTA DE CALAMAR 4 SOBRES ROYAL",
  "TOMATE ENTERO MARTINETE 400",
  "TOMATE ENTERO MARTINETE 810",
  "TOMATE FRITO B ORLANDO 3X212G",
  "TOMATE FRITO BRICK ORLANDO 350GR",
  "TOMATE FRITO MARTINETE 3X200G",
  "TOMATE FRITO MARTINETE 350G",
  "TOMATE FRITO MARTINETE 800G",
  "TOMATE TRITURADO APIS 800",
  "TOMILLO LA BARRACA",
  "TORTELLINI CARNE GALLO 250 GR",
  "TOSTAITOS SEVILLANAS",
  "TOSTAITOS SEVILLANAS 90GR",
  "TRIKERS 100G DORITOS",
  "TUBO CONDENSADA CHOVI 450G",
  "VACHERIN 1 LITRO SOMOSIERRA",
  "VASO POREX 7 OZ 200CC B/50",
  "VEREDEJO DELICATA 3/4",
  "VERMUTS MARTINI B DULCE 1 L.",
  "VIÑA ALBALI RESERVA 3/4",
  "VINAGRE GOURMET JEREZ BOT 250ML",
  "VINAGRE GOURMET MANZANA 1 L",
  "VINAGRE GOURMET MODENA BOT 250 ML",
  "VINAGRE MANZANA PRIMA 3/4",
  "VINO B CASTILLO S DIEGO 3/4",
  "VINO BLANCO DON SIMON 1L",
  "VINO BLANCO ELEGIDO 1L",
  "VINO CANASTA CREAM 75 CL",
  "VINO COCINA EL GUISO 0.70 C.",
  "VINO SOLERA 1847 3/4",
  "VINO TINTO D.O RIOJA CAMPOVIEJO 70C",
  "VINO TINTO ELEGIDO 1L",
  "VINO TINTO EMILIO MORO 2022 75CL",
  "VINO TINTO PROTOS COSECHA 3/4",
  "VINO TINTO SOLDEPEÑAS 1 L.",
  "VIVO GATO BUEY 415G",
  "VIVO PERRO POLLO LT 830",
  "VODKA ABSOLUT 70 CL",
  "VODKA CARAMELO GECKO 0.70 L 30º",
  "VODKA CIROC APLLE 0.7",
  "VODKA ERISTOFF 70CL",
  "VVH VODK CARAMEL RIVES 70CL",
  "WALKER 200 ML ( PETACA )",
  "WALKER BLACK LABEL 70 CL",
  "WALKER NEGRO 1L",
  "WALKER ROJO 1L",
  "WHISKY BALLANTINES 0.70",
  "WHISKY CHIVAS REGAL 0.70",
  "WHISKY DYC 5 AÑOS 70 CL",
  "WHISKY JACK DANIEL 200 ML ( PETACA )",
  "WHISKY JACK DANIELS 3/4",
  "WHISKY JACK DANIELS MINIATURA",
  "WHISKY J&B 200 ML ( PETACA )",
  "WHISKY J&B 70 CL.",
  "WHISKY J.B. MINIATURA",
  "WHISKY JHONNIE WALKER E/ROJA 3/4",
  "WHISKY JHONNIE WALKER E/ROJA MINIATURA",
  "WHISKY WHITE LABEL 70 CL.",
  "WHISKY WHITE LABEL- LITRO-",
  "WHISKY WHITE LABEL MINIATURA",
  "YOGO ICE 10UDS",
  "Z. BIOFRUTA PASCUAL DARK P/3",
  "Z. BIOFRUTA PASCUAL MEDITERRANEO P/3",
  "Z. BIOFRUTA PASCUAL PACIFICO P/3",
  "Z. BIOFRUTA PASCUAL TROPICAL P/3",
  "Z.BIOFRUTA PASCUAL IBIZA PARAISO P-3",
  "ZAMBA FRUTAS SURTIDAS P10",
  "ZANAHORIA GOURMET TIRAS 180 GR",
  "ZUMO 100X100 D.SIMON MELOCOTON 1 L (602)",
  "ZUMO 100X100 D.SIMON NARANJA 1 L.(600)",
  "ZUMO 100X100 D.SIMON PIÑA 1 L (601)",
  "ZUMO D SIMON PIÑA 200 P6 (3574)",
  "ZUMO D.SIMON MELOCOTON P6 200 (3575)",
  "ZUMO DON SIMON NARANJA 200 P-6 (3039)",
  "ZUMO JUVER NARANJA 850 ML",
  "ÑORAS SECAS LA BARRACA"
];

];

const normalizeProductNameForCompare = (text) =>
  text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9ñ]+/gi, "")
    .trim();

const visibleProductNamesForCompare = new Set(
  departments.flatMap((department) =>
    department.products.map((name) => normalizeProductNameForCompare(name))
  )
);

const hiddenProducts = [...new Set(hiddenProductsRaw)]
  .filter(
    (name) =>
      !visibleProductNamesForCompare.has(normalizeProductNameForCompare(name))
  )
  .sort((a, b) => a.localeCompare(b, "es"));

const hiddenProductsUnique = hiddenProducts;

];

const visibleProducts = departments.flatMap((department) =>
  department.products.map((name) => ({
    id: `${department.name}-${name}`,
    name,
    department: department.name,
    hidden: false,
  }))
);

const normalizeForCompare = (text) =>
  text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9ñ]+/gi, "")
    .trim();

const visibleProductNamesForCompare = new Set(
  visibleProducts.map((product) => normalizeForCompare(product.name))
);

const hiddenProductsUnique = [...new Set(hiddenProductsRaw)]
  .filter((name) => !visibleProductNamesForCompare.has(normalizeForCompare(name)))
  .sort((a, b) => a.localeCompare(b, "es"));

const hiddenProductsFormatted = hiddenProductsUnique.map((name) => ({
  id: `ARTÍCULOS BUSCADOS-${name}`,
  name,
  department: "ARTÍCULOS BUSCADOS",
  hidden: true,
}));

const products = [...visibleProducts, ...hiddenProductsFormatted];

export default function App() {
  useEffect(() => {
    let viewport = document.querySelector("meta[name=viewport]");

    if (!viewport) {
      viewport = document.createElement("meta");
      viewport.setAttribute("name", "viewport");
      document.head.appendChild(viewport);
    }

    viewport.setAttribute(
      "content",
      "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    );
  }, []);

  const [quantities, setQuantities] = useState({});
  const [customerName, setCustomerName] = useState("");
  const [notes, setNotes] = useState("");
  const [search, setSearch] = useState("");

  const normalizeText = (text) =>
    text
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .trim();

  const productMatchesSearch = (product, searchText) => {
    const normalizedProduct = normalizeText(product);
    const searchWords = normalizeText(searchText)
      .split(/[^a-z0-9ñ]+/i)
      .filter(Boolean);

    return searchWords.every((searchWord) =>
      normalizedProduct.includes(searchWord)
    );
  };

  const filteredDepartments = useMemo(() => {
    const cleanSearch = search.trim();

    const visibleDepartments = departments
      .map((department) => ({
        ...department,
        products: cleanSearch
          ? department.products.filter((product) =>
              productMatchesSearch(product, cleanSearch)
            )
          : department.products,
      }))
      .filter((department) => department.products.length > 0);

    if (cleanSearch.length < 2) {
      return visibleDepartments;
    }

    const hiddenMatches = hiddenProductsUnique.filter((product) =>
      productMatchesSearch(product, cleanSearch)
    );

    if (hiddenMatches.length > 0) {
      visibleDepartments.push({
        name: "ARTÍCULOS BUSCADOS",
        products: hiddenMatches,
      });
    }

    return visibleDepartments;
  }, [search]);

  const selectedItems = useMemo(() => {
    return products
      .map((product) => ({
        ...product,
        cajas: Number(quantities[product.id]?.cajas || 0),
        unidades: Number(quantities[product.id]?.unidades || 0),
      }))
      .filter((product) => product.cajas > 0 || product.unidades > 0);
  }, [quantities]);

  const updateQuantity = (productId, field, value) => {
    const cleanValue = value.replace(/[^0-9]/g, "");
    setQuantities((current) => ({
      ...current,
      [productId]: {
        ...current[productId],
        [field]: cleanValue,
      },
    }));
  };

  const closeKeyboardOnEnter = (event) => {
    if (event.key === "Enter") {
      event.currentTarget.blur();
    }
  };

  const clearOrder = () => {
    setQuantities({});
    setCustomerName("");
    setNotes("");
    setSearch("");
  };

  const createWhatsAppMessage = () => {
    const lines = ["Nuevo pedido", ""];

    if (customerName.trim()) {
      lines.push(`Cliente: ${customerName.trim()}`, "");
    }

    selectedItems.forEach((item) => {
      const parts = [];
      if (item.cajas > 0) parts.push(`*${item.cajas} cajas*`);
      if (item.unidades > 0) parts.push(`*${item.unidades} unidades*`);

      lines.push(`- ${item.name}: ${parts.join(" / ")}`);
      lines.push("");
    });

    lines.push("");

    if (notes.trim()) {
      lines.push(`Observaciones: ${notes.trim()}`, "");
    }

    lines.push("Enviado desde el formulario de pedidos");
    return encodeURIComponent(lines.join("\n"));
  };

  const sendOrder = () => {
    if (selectedItems.length === 0) {
      alert("Introduce al menos una cantidad antes de enviar el pedido.");
      return;
    }

    window.open(
      `https://wa.me/${WHATSAPP_NUMBER}?text=${createWhatsAppMessage()}`,
      "_blank"
    );

    clearOrder();
  };

  return (
    <div style={styles.page}>
      <div style={styles.container}>
        <header style={styles.header}>
          <div style={styles.iconBox}>
            <ShoppingCart size={28} />
          </div>
          <div>
            <h1 style={styles.title}>Pedido online Cash Lojo</h1>
            <p style={styles.subtitle}>
              Escribe cantidades en Unidades o Cajas y envía el pedido por WhatsApp.
            </p>
          </div>
        </header>

        <div style={styles.cardSticky}>
          <label style={styles.label}>Nombre o referencia del cliente</label>
          <input
            value={customerName}
            onChange={(event) => setCustomerName(event.target.value)}
            placeholder="Opcional"
            style={styles.input}
          />

          <label style={styles.label}>Buscar artículo</label>
          <div style={styles.searchAndSendRow}>
            <div style={styles.searchBoxCompact}>
              <Search size={20} style={styles.searchIcon} />
              <input
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                placeholder="Buscar..."
                style={styles.searchInput}
              />
            </div>

            <button onClick={sendOrder} style={styles.stickyWhatsappButton}>
              <Send size={18} /> WhatsApp
            </button>
          </div>
        </div>

        {filteredDepartments.map((department) => (
          <section key={department.name} style={styles.section}>
            <div style={styles.sectionHeader}>
              <h2 style={styles.sectionTitle}>{department.name}</h2>
            </div>

            <div style={styles.gridHeader}>
              <div>Cajas</div>
              <div>Unid.</div>
              <div style={{ textAlign: "left" }}>Artículo</div>
            </div>

            {department.products.map((productName) => {
              const productId = `${department.name}-${productName}`;

              return (
                <div key={productId} style={styles.row}>
                  <input
                    inputMode="numeric"
                    enterKeyHint="done"
                    value={quantities[productId]?.cajas || ""}
                    onChange={(event) =>
                      updateQuantity(productId, "cajas", event.target.value)
                    }
                    onKeyDown={closeKeyboardOnEnter}
                    placeholder="0"
                    style={styles.qtyInput}
                  />

                  <input
                    inputMode="numeric"
                    enterKeyHint="done"
                    value={quantities[productId]?.unidades || ""}
                    onChange={(event) =>
                      updateQuantity(productId, "unidades", event.target.value)
                    }
                    onKeyDown={closeKeyboardOnEnter}
                    placeholder="0"
                    style={styles.qtyInput}
                  />

                  <p style={styles.productName}>{productName}</p>
                </div>
              );
            })}
          </section>
        ))}

        <div style={styles.card}>
          <label style={styles.label}>Observaciones</label>
          <textarea
            value={notes}
            onChange={(event) => setNotes(event.target.value)}
            placeholder="Opcional"
            rows={3}
            style={styles.textarea}
          />

          <div style={styles.summary}>
            <strong>Resumen:</strong> {selectedItems.length} artículos con cantidad.
          </div>

          <button onClick={sendOrder} style={styles.primaryButton}>
            <Send size={20} /> Enviar por WhatsApp
          </button>

          <button onClick={clearOrder} style={styles.secondaryButton}>
            <Trash2 size={20} /> Borrar pedido
          </button>
        </div>
      </div>
    </div>
  );
}

const styles = {
  page: {
    minHeight: "100vh",
    background: "#f1f5f9",
    padding: "16px",
    color: "#0f172a",
    fontFamily: "Arial, sans-serif",
  },
  container: {
    maxWidth: "1100px",
    margin: "0 auto",
  },
  header: {
    background: "white",
    padding: "20px",
    borderRadius: "18px",
    display: "flex",
    gap: "14px",
    alignItems: "center",
    marginBottom: "16px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.08)",
  },
  iconBox: {
    background: "#0f172a",
    color: "white",
    borderRadius: "16px",
    padding: "12px",
    display: "flex",
  },
  title: { margin: 0, fontSize: "24px" },
  subtitle: { margin: "6px 0 0", color: "#475569", fontSize: "14px" },
  cardSticky: {
    position: "sticky",
    top: "8px",
    zIndex: 10,
    background: "white",
    padding: "16px",
    borderRadius: "18px",
    marginBottom: "18px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.08)",
  },
  card: {
    background: "white",
    padding: "18px",
    borderRadius: "18px",
    marginTop: "18px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.08)",
  },
  label: {
    display: "block",
    fontWeight: "bold",
    fontSize: "13px",
    marginBottom: "6px",
    marginTop: "8px",
  },
  input: {
    width: "100%",
    padding: "11px",
    borderRadius: "12px",
    border: "1px solid #cbd5e1",
    fontSize: "16px",
    boxSizing: "border-box",
  },
  searchAndSendRow: {
    display: "grid",
    gridTemplateColumns: "1fr 118px",
    gap: "8px",
    alignItems: "center",
  },
  searchBoxCompact: { position: "relative", minWidth: 0 },
  searchIcon: { position: "absolute", left: "12px", top: "11px", color: "#64748b" },
  searchInput: {
    width: "100%",
    padding: "11px 12px 11px 40px",
    borderRadius: "12px",
    border: "1px solid #cbd5e1",
    fontSize: "16px",
    boxSizing: "border-box",
  },
  section: {
    background: "white",
    borderRadius: "18px",
    overflow: "hidden",
    marginBottom: "18px",
    boxShadow: "0 1px 6px rgba(0,0,0,0.08)",
  },
  sectionHeader: { background: "#0f172a", color: "white", padding: "12px 16px" },
  sectionTitle: { margin: 0, fontSize: "18px", textTransform: "uppercase" },
  gridHeader: {
    display: "grid",
    gridTemplateColumns: "80px 80px 1fr",
    gap: "8px",
    background: "#e2e8f0",
    padding: "10px",
    fontSize: "12px",
    fontWeight: "bold",
    textAlign: "center",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "80px 80px 1fr",
    gap: "8px",
    alignItems: "center",
    padding: "9px 10px",
    borderTop: "1px solid #e2e8f0",
  },
  qtyInput: {
    width: "100%",
    padding: "8px 4px",
    borderRadius: "12px",
    border: "1px solid #cbd5e1",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: "16px",
    boxSizing: "border-box",
  },
  productName: { margin: 0, fontSize: "16px", fontWeight: "600" },
  textarea: {
    width: "100%",
    padding: "11px",
    borderRadius: "12px",
    border: "1px solid #cbd5e1",
    fontSize: "16px",
    boxSizing: "border-box",
  },
  summary: {
    background: "#e2e8f0",
    padding: "12px",
    borderRadius: "12px",
    margin: "14px 0",
    fontSize: "14px",
  },
  primaryButton: {
    width: "100%",
    height: "50px",
    border: "none",
    borderRadius: "12px",
    background: "#0f172a",
    color: "white",
    fontSize: "16px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginBottom: "10px",
  },
  stickyWhatsappButton: {
    width: "100%",
    height: "44px",
    border: "none",
    borderRadius: "12px",
    background: "#22c55e",
    color: "white",
    fontSize: "13px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    whiteSpace: "nowrap",
  },
  secondaryButton: {
    width: "100%",
    height: "50px",
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    background: "white",
    color: "#0f172a",
    fontSize: "16px",
    fontWeight: "bold",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
};
